### ISSUE TITLE
Getting three instances browser

### ISSUE THREAD

**Issue by sahutarun** [serenity-bdd/serenity-demos#38]
Hi Johh,

I am getting three browser. Even though I havn't used @Managed in the stepdefination.

Can you please look into my project and see what went wrong?

https://github.com/sahutarun/Serenity?files=1

**Comment by wakaleo** [comment]
The project, when checked out, fails to run because there are no default urls defined for the page object.

As this is an open source project, we can only provide limited support for specific project issues. If you need more personalised assistance, I would advice considering one of our mentoring packages: https://johnfergusonsmart.com/serenity-bdd-mentoring/

**Comment by sahutarun** [comment]
May my last commit cause an issue as thete were two pages, the one has this default url. The actuak problem is it keeps on launching the browsers 2-4 times. Please help as I am not getting any resources.
